config/routes.rb
Tempaccts::Application.routes.draw do
  resources :account_group_tempaccts

  resources :account_groups

  resources :account_types

  resources :roles

  devise_for :users, controllers: {sessions: "sessions"}, :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :acct_types

  resources :tempaccts

  

  match 'search', :to => 'tempaccts#search', :via => [:get, :post], :as => 'search'

  root :to => 'tempaccts#index'
end

app/models/tempacct.rb
class Tempacct < ActiveRecord::Base
  validates :firstname, :surname, :uid, :passwd, :expiry_date, :owner, :account_type_id, :presence => true
  validates :ftp_login, :in_ldap, :printing, :inclusion => { :in => [true, false, 0, 1], :message => "Error: Boolean value must be 0 or 1" }
  validates :uid, :uniqueness => true
  #validates :description, :presence => true
  validate :expiry_date_cannot_be_in_the_past, on: :create
  validate :expiry_date_cannot_too_far_in_future
  validate :passwd_validity

  has_one :account_type
  #attr_accessor :account_type_id

  def fullname
    "#{firstname} #{surname}"
  end
  # Check http://edgeguides.rubyonrails.org/active_record_validations.html#custom-methods
  def expiry_date_cannot_be_in_the_past
    if expiry_date < Date.today
      errors.add(:expiry_date, "can't be in the past")
    end
  end
  
  # Check that the expiry date is not beyond the max for the account type
  def expiry_date_cannot_too_far_in_future
    ed = AccountType.max_expiry?(account_type_id)
    if expiry_date > ed
      atn = AccountType.account_type_name(account_type_id)
      errors.add(:expiry_date, "can't exceed #{atn} account type limit of #{ed.to_s(:my_date)}.")
    end
  end

  def passwd_validity
    if passwd.length < 8
      errors.add(:passwd, "must contain at least 8 characters.")
    end
    if ! passwd.match(/\A(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[\W_ ]).{8,}\z/)
      errors.add(:passwd, "must contain upper and lower case, a number and a punctuation character.")
    end
  end
  # Filter account names by their first letter - used for alphabetic pagination
  scope :by_letter, ->(initial) {where("surname LIKE \'#{initial}%\'").order(:surname) }
end

app/controllers/tempaccts_controller.rb
class TempacctsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index, :search]
  before_action :set_tempacct, only: [:show, :edit, :update, :destroy]
  before_action :set_initials, only: [:index, :search]
  after_action :log_update, only: [:create, :update, :destroy]
  #load_and_authorize_resource

  # GET /tempaccts
  # GET /tempaccts.json
  def index
      if(params[:search]) then
      search_condition = "%" + params[:search] + "%"
      session[:search] = params[:search]
    elsif(session[:search])
      search_condition = "%" + session[:search] + "%"
    else
      search_condition = "%"
      session[:search] = nil
    end

    session[:tempacct_letter] = nil
    session[:tempacct_letter] ||= params[:q]

    @tempaccts = Tempacct.by_letter(session[:tempacct_letter]).paginate :page => params[:page], :per_page => 25
    session[:tempaccts_page] = (params[:page]) ? tempaccts_url+"?page="+params[:page] : tempaccts_url
  end

  # GET /tempaccts/1
  # GET /tempaccts/1.json
  def show
    if !session[:tempacct_page] then session[:tempacct_page] = tempaccts_url end
      begin
      @tempacct = Tempacct.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attmpt to access invalid alias id #{params[:id]}"
      redirect_to tempacctes_url, :notice => "Invalid or non-existent temporary account record"
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @tempacct }
      end
    end
  end

  # GET /tempaccts/new
  def new
    @tempacct = Tempacct.new
    authorize! :new, @tempacct
    if !session[:tempacct_page] then session[:tempacct_page] = tempaccts_url end
  end

  # GET /tempaccts/1/edit
  def edit
    @tempacct = Tempacct.find(params[:id])
    authorize! :edit, @tempacct
    if !session[:tempacct_page] then session[:tempacct_page] = tempaccts_url end
  end

  # POST /tempaccts
  # POST /tempaccts.json
  def create
    @tempacct = Tempacct.new(tempacct_params)
    authorize! :create, @tempacct
    respond_to do |format|
      if @tempacct.save
        #format.html { redirect_to @tempacct, notice: 'Tempacct was successfully created.' }
        format.html { redirect_to session[:tempacct_page], notice: 'Temporary account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tempacct }
      else
        format.html { render action: 'new' }
        format.json { render json: @tempacct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tempaccts/1
  # PATCH/PUT /tempaccts/1.json
  def update
  begin
    authorize! :update, @tempacct
    respond_to do |format|
      if @tempacct.update(tempacct_params)
        format.html { redirect_to @tempacct, notice: 'Tempacct was successfully updated.' }
        #format.html { redirect_to session[:tempacct_page], notice: 'Temporary account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tempacct.errors, status: :unprocessable_entity }
      end
    end
    
    rescue ActiveRecord::StatementInvalid
      logger.error "Invalid database update statement."
      redirect_to session[:tempacct_page], :notice => "Error: Invalid database update statement."
    end
  end

  # DELETE /tempaccts/1
  # DELETE /tempaccts/1.json
  def destroy
    authorize! :destroy, @tempacct
    @tempacct.destroy
    respond_to do |format|
      #format.html { redirect_to tempaccts_url }
      format.html{redirect_to session[:tempacct_page]}
      format.json { head :no_content }
    end
  end

  # GET /tempaccts/search
  def search
    if(params[:search]) then
      search_condition = "%" + params[:search] + "%"
      session[:search] = params[:search]
    else
      search_condition = "%"
      session[:search] = nil
    end
    #@tempaccts = Tempacct.paginate :page => params[:page], :order => 'uid asc', :per_page => 25, :conditions => ['uid LIKE ? OR description LIKE ? OR name LIKE ? OR name LIKE ?', search_condition, search_condition, search_condition, search_condition]
    @tempaccts = Tempacct.order("uid asc").paginate :page => params[:page], :per_page => 25, :conditions => ['uid LIKE ? OR description LIKE ? OR firstname LIKE ? OR surname LIKE ? OR expiry_date LIKE ?', search_condition, search_condition, search_condition, search_condition, search_condition]

    respond_to do |format|
      format.html { render action: 'index' }
      format.xml  { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tempacct
      @tempacct = Tempacct.find(params[:id])
    end
    def set_initials
      @first_letters = Tempacct.select("DISTINCT LOWER(SUBSTR(tempaccts.surname, 1, 1)) AS surname").order("surname").collect{|fl| "#{fl.surname}"}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tempacct_params
      params.require(:tempacct).permit(:firstname, :surname, :uid, :passwd, :owner, :expiry_date, :account_type_id, :ftp_login, :in_ldap, :printing, :description)
  end
  def log_update
    @at = AccountType.account_type_name(@tempacct.account_type_id)
    log_msg = "id: #{@tempacct.id}\nfirstname#{@tempacct.firstname}\nsurname#{@tempacct.surname}\nowner: #{@tempacct.owner}\nexpiry_date: #{@tempacct.expiry_date}\naccount_type:#{@at}\nftp_login:  #{@tempacct.ftp_login}\nin_ldap: #{@tempacct.in_ldap}\n\nprinting: #{@tempacct.printing}\ndescription: #{@tempacct.description}" 
    ActivityLog.create(:item_type => controller_name.classify, :item_id => @tempacct.id, :act_action => action_name, :updated_by => current_user.username, :activity => log_msg, :act_tstamp => Time.now)
  end
end

app/helpers/tempaccts_helper.rb
module TempacctsHelper
end

app/views/tempaccts/_by_letter.html.erb
<% @first_letters.each do |lt| %>
  <%= lt != (session[:tempacct_letter]) ? link_to(lt, tempaccts_url+"?q="+lt )+" " : "<span class='digg_pagination disabled'>#{lt}</span>".html_safe  %>
<% end %>
<%= link_to('All', tempaccts_url+"?q=" ) %>

app/views/tempaccts/_form.html.erb
<%= form_for(@tempacct) do |f| %>
  <% if @tempacct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tempacct.errors.count, "error") %> prohibited this tempacct from being saved:</h2>

      <ul>
      <% @tempacct.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="display: inline; float: left; width: 75%;">
  <fieldset><legend>Account details</legend><dl>

<div> <!-- wrapper around account details and help divs -->
  <div class="field" style="float: left;">
    <%= f.label :firstname %> (Required)<br />
    <%= f.text_field :firstname, :class => "tempaccts" %><br />
	<%= f.label :surname %> (Required)<br />
    <%= f.text_field :surname, :class => "tempaccts" %><br />
	<%= f.label :owner %><br />
    <%= f.text_field :owner, :class => "tempaccts" %><br />
	<%= f.label :expiry_date %> (Required)<br />
	<% if @tempacct.expiry_date %>
    <%= f.date_select :expiry_date, :order => [:day, :month, :year ], :selected => @tempacct.expiry_date, :start_year => Time.now.year, :end_year => @tempacct.expiry_date.year + 5 %>
	<% else %>
	<%= f.date_select :expiry_date, :order => [:day, :month, :year ], :default => 1.year.from_now, :start_year => Time.now.year, :end_year => Time.now.year+5 %><br />
	<% end %>
  </div>
  <div class="field" style="float: left; width: 35%;">
    <%= f.label :uid %> (Required)<br />
    <%= f.text_field :uid, :class => "tempaccts" %><br />
    <%= f.label :passwd, "Password" %> (Required)<br />
    <%= f.text_field :passwd, :class => "tempaccts" %><br />
	<%= f.label :account_type_id, "Account type" %> (Required)<br />
	<%= f.collection_select :account_type_id, AccountType.order(:name), :id, :max_exp_label, {:selected => @tempacct.account_type_id,:prompt => 'Please select'} %><br /
  </div>
  </dl>
  </fieldset>
  </div>

  <div style="clear: both;"></div>
  
  <div style="display: inline; float: left; width: 75%;">
  <fieldset><legend>Directory Settings</legend>
   <div class="field" style="float: left%;">
	<%= f.label :ftp_login %>&nbsp;
    <%= f.check_box :ftp_login %>&nbsp;
	<%= f.label :in_ldap, "LDAP access" %>&nbsp;
    <%= f.check_box :in_ldap %>&nbsp;
	<%= f.label :printing %>&nbsp;
    <%= f.check_box :printing %>
	</div
  </div>
  </fieldset>
  </div>

  <div style="clear: both;"></div>

  <div style="display: inline; float: left; width: 75%;">
  <fieldset><legend>Additional information</legend><dl>
  <div class="field" style="float: left; width: auto;">
  
    <%= f.label :description, "Please include details of the support call reference along why the account is needed." %><br />
    <%= f.text_area :description, :rows => 5, :cols => 40, :class => "tempaccts" %>
  </div>
  </dl>
  </fieldset>
  </div>

  <div style="clear: both;"></div>

  <div class="actions">
    <%= f.submit :class => 'button' %>
  </div>
<% end %>
  

app/views/tempaccts/edit.html.erb
<div id="mainbody">
<h2>Editing tempacct</h2>

<%= render 'form' %>

<div class="tempaccts">
<%= link_to 'Show', @tempacct %> |
<%= link_to 'Back', tempaccts_path %>
  <div style="clear: both;"></div>
</div>
</div>

app/views/tempaccts/index.html.erb
<div id="mainbody">
<h2>Listing temporary accounts</h2>
<div class="digg_pagination">
<%= will_paginate @tempaccts %>&nbsp;
<% if can? :create, Tempacct %>
<%= link_to 'New Temporary account', new_tempacct_path %>
<% end %>
<p style="clear: both">
<%= render :partial => 'by_letter' %><br />
</p>
</div>
<p style="clear: both">
<table class="tempaccts" cellspacing="0">
  <thead>
    <tr class="tempaccts">
      <th>Uid</th>
	  <th></th>
      <th>Name</th>
	  <th>Account type</th>
      <th>Expiry date</th>
      <th>LDAP</th>
      <th>Ftp </th>
      <th>Printing</th>
	  <% if can? :destroy, Tempacct %>
      <th>Delete</th>
	  <% end %>
    </tr>
  </thead>


  <tbody>
    <% @tempaccts.each do |tempacct| %>
      <tr class="<%= cycle('ma_row_dark', 'ma_row_light') %>">
      	<td><%= link_to_modal tempacct.uid, tempacct %></td>
        <td>
        <% if can? :edit, Tempacct %>
        <%= link_to image_tag("edit-icon.png", :size => "16x16", :title => "Edit details"), edit_tempacct_path(tempacct) %>
        <% end %>
        </td>
        <td><%= tempacct.firstname + " " + tempacct.surname %></td>
		<td><%= AccountType.find(tempacct.account_type_id).name %></td>
        <td><%= tempacct.expiry_date.to_s(:my_date) %></td>
        <td><%= tempacct.in_ldap == 1? 'Y' : 'N' %></td>
        <td><%= tempacct.ftp_login == 1 ? 'Y' : 'N' %></td>
        <td><%= tempacct.printing == 1 ? 'Y' : 'N' %></td>
		<% if can? :destroy, Tempacct %>
        <%= render :partial => "shared/delete_link", :object => tempacct, :locals => {:display => "Delete #{tempacct.uid}" } %>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<p>
<div class="digg_pagination">
<%= will_paginate @tempaccts %>&nbsp;
<% if can? :create, Tempacct %>
<%= link_to 'New Temporary account', new_tempacct_path %>
<% end %>
</div>
</p>
</div>

app/views/tempaccts/new.html.erb
<div id="mainbody">
<h2>New tempacct</h2>

<%= render 'form' %>

<div class="tempaccts">
<%= link_to 'Back', tempaccts_path %>
</div>
</div>

app/views/tempaccts/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @tempacct.fullname %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @tempacct.uid %>
</p>

<p>
  <strong>Password:</strong>
  ********
</p>

<p>
  <strong>Owner:</strong>
  <%= @tempacct.owner %>
</p>

<p>
  <strong>Expiry date:</strong>
  <%= @tempacct.expiry_date.to_s(:my_date) %>
</p>

<p>
  <strong>Account type:</strong>
  <%= AccountType.account_type_name(@tempacct.account_type_id) %>
</p>

<p>
  <strong>FTP login:</strong>
  <%= @tempacct.ftp_login %>
</p>

<p>
  <strong>LDAP:</strong>
  <%= @tempacct.in_ldap %>
</p>

<p>
  <strong>Printing access:</strong>
  <%= @tempacct.printing %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tempacct.description.html_safe() %>
</p>

<div class="tempaccts">
<%= link_to 'Edit', edit_tempacct_path(@tempacct) %> |
<%= link_to 'Back', tempaccts_path %>
</div>