config/routes.rb
Tempaccts::Application.routes.draw do
  resources :account_group_tempaccts

  resources :account_groups

  resources :account_types

  resources :roles

  devise_for :users, controllers: {sessions: "sessions"}, :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :acct_types

  resources :tempaccts

  

  match 'search', :to => 'tempaccts#search', :via => [:get, :post], :as => 'search'

  root :to => 'tempaccts#index'
end

app/controllers/account_types_controller.rb
class AccountTypesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index, :search]
  before_action :set_account_type, only: [:show, :edit, :update, :destroy]
  after_action :log_update, only: [:create, :update, :destroy]

  # GET /account_types
  # GET /account_types.json
  def index
    @account_types = AccountType.order("name asc").paginate :page => params[:page], :per_page => 25
  end

  # GET /account_types/1
  # GET /account_types/1.json
  def show
  end

  # GET /account_types/new
  def new
    #authorize! :create, @account_type
    @account_type = AccountType.new
  end

  # GET /account_types/1/edit
  def edit
  end

  # POST /account_types
  # POST /account_types.json
  def create
    @account_type = AccountType.new(account_type_params)
    authorize! :create, @account_type

    respond_to do |format|
      if @account_type.save
        format.html { redirect_to @account_type, notice: 'Account type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @account_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_types/1
  # PATCH/PUT /account_types/1.json
  def update
    authorize! :update, @account_type
    respond_to do |format|
      if @account_type.update(account_type_params)
        format.html { redirect_to @account_type, notice: 'Account type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_types/1
  # DELETE /account_types/1.json
  def destroy
    authorize! :destroy, @account_type
    @account_type.destroy
    respond_to do |format|
      format.html { redirect_to account_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_type
      @account_type = AccountType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_type_params
      params.require(:account_type).permit(:name, :description, :max_expiry)
  end
  def log_update
    log_msg = "id: #{@account_type.id}\nname: #{@account_type.name}\ndescription: #{@account_type.description}\nmax_expiry: #{@account_type.max_expiry}\n" 
    ActivityLog.create(:item_type => controller_name.classify, :item_id => @account_type.id, :act_action => action_name, :updated_by => current_user.username, :activity => log_msg, :act_tstamp => Time.now)
  end
end

app/helpers/account_types_helper.rb
module AccountTypesHelper
end

app/views/account_types/_form.html.erb
<%= form_for(@account_type) do |f| %>
  <% if @account_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_type.errors.count, "error") %> prohibited this account_type from being saved:</h2>

      <ul>
      <% @account_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="display: inline; float: left; width: 60%;">
  <fieldset><legend>Account type details</legend><dl>

  <div> <!-- wrapper around account details and help divs -->
  <div class="field" style="float: left;">
    <%= f.label :name %> (Required)<br />
    <%= f.text_field :name, :class => "tempaccts" %><br />
	<%= f.label :max_expiry, "Max expiry period" %> (Required)<br />
	<% if @account_type.max_expiry %>
    <%= f.date_select :max_expiry,  :order => [:day, :month, :year ], :selected => @account_type.max_expiry, :start_year => @account_type.max_expiry.year, :end_year => @account_type.max_expiry.year+10 %>
	<% else %>
	<%= f.date_select :max_expiry,  :order => [:day, :month, :year ], :default => 1.year.from_now, :start_year => Time.now.year, :end_year => Time.now.year+10 %>
	<% end%>
  </div>
  </dl>
  </fieldset>
  </div>
  <div style="clear: both;"></div>

  <div style="display: inline; float: left; width: 60%;">
  <fieldset><legend>Additional information</legend><dl>
  <div class="field" style="float: left; width: auto;">
    <%= f.label :description, "Brief description of the account type.", :class => "tempaccts"  %><br />
    <%= f.text_area :description, :rows => 5, :cols => 40, :class => "tempaccts" %>
  </div>
  </dl>
  </fieldset>
  </div>

  <div style="clear: both;"></div>

  <div class="actions">
    <%= f.submit :class => 'button' %>
  </div>
<% end %>

app/views/account_types/edit.html.erb
<div id="mainbody">
<h2>Editing account type</h2>

<%= render 'form' %>

<div class="tempaccts">
<%= link_to_modal 'Show', @account_type %> |
<%= link_to 'Back', account_types_path %>
</div>
</div>

app/views/account_types/index.html.erb
<div id="mainbody">
<h2>Listing account types</h2>
<div class="digg_pagination">
<%= will_paginate @account_types %>&nbsp;
<% if can? :create, AccountType %>
<%= link_to 'New account type', new_account_type_path %>
<% end %>
</div>
<p style="clear: both">
<br />	
<table class="tempaccts" cellspacing="0">
  <thead>
    <tr>
      <th>Name</th>
	  <th></th>
      <th>Description</th>
      <th>Max expiry</th>
      <% if can? :destroy, Tempacct %>
      <th>Delete</th>
	  <% end %>
    </tr>
  </thead>

  <tbody>
    <% @account_types.each do |account_type| %>
      <tr class="<%= cycle('ma_row_light', 'ma_row_dark') %>">
      	<td><%= link_to_modal account_type.name, account_type %></td>
        <td>
        <% if can? :edit, AccountType %>
        <%= link_to image_tag("edit-icon.png", :size => "16x16", :title => "Edit details"), edit_account_type_path(account_type) %>
        <% end %>
        </td>
        <td><%= account_type.description.html_safe() %></td>
        <td style="width: 20%"><%= account_type.max_expiry.to_s(:my_date) %></td>
        <% if can? :destroy, AccountType %>
        <%= render :partial => "shared/delete_link", :object => account_type, :locals => {:display => "Delete #{account_type.name}" } %>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<p></p>
<div class="digg_pagination">
<%= will_paginate @account_types %>&nbsp;
<% if can? :create, AccountType %>
<%= link_to 'New account type', new_account_type_path %>
<% end %>
</div>
</p>

app/views/account_types/new.html.erb
<div id="mainbody">
<h2>New account type</h2>

<%= render 'form' %>

<div class="tempaccts">
<%= link_to 'Back', account_types_path %>
</div>
</div>

app/views/account_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @account_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @account_type.description.html_safe() %>
</p>

<p>
  <strong>Max expiry:</strong>
  <%= @account_type.max_expiry.to_s(:my_date) %>
</p>

<div class="tempaccts">
<%= link_to 'Edit', edit_account_type_path(@account_type) %> |
<%= link_to 'Back', account_types_path %>
</div>