config/routes.rb
Tempaccts::Application.routes.draw do
  resources :account_group_tempaccts

  resources :account_groups

  resources :account_types

  resources :roles

  devise_for :users, controllers: {sessions: "sessions"}, :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :acct_types

  resources :tempaccts

  

  match 'search', :to => 'tempaccts#search', :via => [:get, :post], :as => 'search'

  root :to => 'tempaccts#index'
end

app/models/account_group.rb
class AccountGroup < ActiveRecord::Base
  has_many :account_group_tempaccts
  has_many :tempaccts
end

app/controllers/account_groups_controller.rb
class AccountGroupsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index, :search]
  before_action :set_account_group, only: [:show, :edit, :update, :destroy]
  after_action :log_update, only: [:create, :update, :destroy]

  # GET /account_groups
  # GET /account_groups.json
  def index
    @account_groups = AccountGroup.order("name asc").paginate :page => params[:page], :per_page => 25
  end

  # GET /account_groups/1
  # GET /account_groups/1.json
  def show
  end

  # GET /account_groups/new
  def new
    @account_group = AccountGroup.new
  end

  # GET /account_groups/1/edit
  def edit
    authorize! :edit, @account_group
  end

  # POST /account_groups
  # POST /account_groups.json
  def create
    @account_group = AccountGroup.new(account_group_params)
    authorize! :create, @account_group

    respond_to do |format|
      if @account_group.save
        format.html { redirect_to @account_group, notice: 'Account group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account_group }
      else
        format.html { render action: 'new' }
        format.json { render json: @account_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_groups/1
  # PATCH/PUT /account_groups/1.json
  def update
    authorize! :create, @account_group
    respond_to do |format|
      if @account_group.update(account_group_params)
        format.html { redirect_to @account_group, notice: 'Account group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_groups/1
  # DELETE /account_groups/1.json
  def destroy
    authorize! :destroy, @account_group
    @account_group.destroy
    respond_to do |format|
      format.html { redirect_to account_groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_group
      @account_group = AccountGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_group_params
      params.require(:account_group).permit(:name, :description, :default_expiry)
    end
    def log_update
      log_msg = "id: #{@account_group.id}\nfirstName#{@account_group.name}\ndefault_expiry: #{@account_group.default_expiry}\n" 
      ActivityLog.create(:item_type => controller_name.classify, :item_id => @account_group.id, :act_action => action_name, :updated_by => current_user.username, :activity => log_msg, :act_tstamp => Time.now)
    end
end

app/helpers/account_groups_helper.rb
module AccountGroupsHelper
end

app/views/account_groups/_form.html.erb
<%= form_for(@account_group) do |f| %>
  <% if @account_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_group.errors.count, "error") %> prohibited this account_group from being saved:</h2>

      <ul>
      <% @account_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="display: inline; float: left; width: 60%;">
  <fieldset><legend>Account type details</legend><dl>

  <div> <!-- wrapper around account details and help divs -->
  <div class="field" style="float: left;">
    <%= f.label :name, "Group name" %> (Required)<br />
    <%= f.text_field :name, :class => "tempaccts" %><br />
    <%= f.label :default_expiry %> (Required)<br />
	<% if @account_group.default_expiry %>
    <%= f.date_select :default_expiry, :order => [:day, :month, :year ],  :selected => @account_group.default_expiry, :start_year => @account_group.default_expiry.year, :end_year => @account_group.default_expiry.year + 10, :class => "tempaccts" %>
	<% else %>
	<%= f.date_select :default_expiry,  :order => [:day, :month, :year ], :default => 1.year.from_now, :start_year => Time.now.year, :end_year => Time.now.year + 10, :class => "tempaccts" %>
	<% end %>
  </div>
  </div>
  </dl>
  </div>
  </fieldset>

  <div style="clear: both;"></div>

  <div style="display: inline; float: left; width: 60%;">
  <fieldset><legend>Additional information</legend><dl>
  <div class="field" style="float: left;">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 5, :cols => 40, :class => "tempaccts" %>
  </div>
  </dl>
  </fieldset>
 
  <div style="clear: both;"></div>
  <div class="actions">
    <%= f.submit :class => 'button' %>
  </div>
<% end %>

app/views/account_groups/edit.html.erb
<div id="mainbody">
<h2>Editing account_group</h2>

<%= render 'form' %>

<div class="tempaccts">
<%= link_to_modal 'Show', @account_group %> |
<%= link_to 'Back', account_groups_path %>
</div>
</div>

app/views/account_groups/index.html.erb
<div id="mainbody">
<h2>Listing account groups</h2>
<div class="digg_pagination">
<%= will_paginate @account_groups %>&nbsp;
<% if can? :create, AccountGroup %>
<%= link_to 'New account group', new_account_group_path %>
<% end %>
</div>
<p style="clear: both">
<br />
<table class="tempaccts" cellspacing="0">
  <thead>
    <tr>
      <th>Name</th>
	  <th></th>
      <th>Description</th>
      <th>Default expiry</th>
      <% if can? :destroy, AccountGroup %>
      <th>Delete</th>
	  <% end %>
    </tr>
  </thead>

  <tbody>
    <% @account_groups.each do |account_group| %>
      <tr class="<%= cycle('ma_row_light', 'ma_row_dark') %>">
      	<td><%= link_to_modal account_group.name, account_group %></td>
        <td>
        <% if can? :edit, AccountGroup %>
        <%= link_to image_tag("edit-icon.png", :size => "16x16", :title => "Edit details"), edit_account_group_path(account_group) %>
        <% end %>
        </td>
        <td><%= account_group.description.html_safe() %></td>
        <td style="width: 15%"><%= account_group.default_expiry.to_s(:my_date) %></td>
        <% if can? :destroy, AccountType %>
        <%= render :partial => "shared/delete_link", :object => account_group, :locals => {:display => "Delete #{account_group.name}" } %>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
<div class="digg_pagination">
<%= will_paginate @account_groups %>&nbsp;
<% if can? :create, AccountGroup %>
<%= link_to 'New account group', new_account_group_path %>
<% end %>
</div>
</p>

app/views/account_groups/new.html.erb
<div id="mainbody">
<h2>New account group</h2>

<%= render 'form' %>

<div class="tempaccts">
<%= link_to 'Back', account_groups_path %>
</div>
</div>

app/views/account_groups/show.html.erb
<div class="mainbody">
<p>
  <strong>Name:</strong>
  <%= @account_group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @account_group.description.html_safe() %>
</p>

<p>
  <strong>Default expiry:</strong>
  <%= @account_group.default_expiry.to_s(:my_date) %>
</p>

<div class="tempaccts">
<%= link_to 'Edit', edit_account_group_path(@account_group) %> |
<%= link_to 'Back', account_groups_path %>
</div>
</div>