config/routes.rb
Tempaccts::Application.routes.draw do
  resources :account_group_tempaccts

  resources :account_groups

  resources :account_types

  resources :roles

  devise_for :users, controllers: {sessions: "sessions"}, :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :acct_types

  resources :tempaccts

  

  match 'search', :to => 'tempaccts#search', :via => [:get, :post], :as => 'search'

  root :to => 'tempaccts#index'
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  attr_reader :user_tokens

  def user_tokens=(ids)
    self.user_ids = ids
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:show, :index]
  after_action :log_update, only: [:create, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    #@roles = role.all
    @roles = Role.order("name asc").paginate :page => params[:page], :per_page => 25
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
    authorize! :edit, @role
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)
    authorize! :create, @role
    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'role was successfully created.' }
        format.json { render action: 'show', status: :created, location: @role }
      else
        format.html { render action: 'new' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    authorize! :update, @role
    
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    authorize! :destroy, @role
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_params
    params.require(:role).permit(:name, :resource_id, :resource_type, user_tokens: [] )
  end
  def log_update
    log_msg = "id: #{@role.id}\nname: #{@role.name}\nresource_id: #{@role.resource_id}\nresource_type: #{@role.resource_type}\nusers: " 
    ActivityLog.create(:item_type => controller_name.classify, :item_id => @role.id, :act_action => action_name, :updated_by => current_user.username, :activity => log_msg, :act_tstamp => Time.now)
    #Rails.logger.debug "DEBUG: #{current_user.username} Updated data: ext #{ext} in subdept #{sdp} for #{@role.user_name}"
  end
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="display: inline; float: left; width: 60%;">
The name field is disabled to prevent blocking access to users of that role.
    <fieldset><legend>Account details</legend>

      <div> <!-- wrapper around account details and help divs -->
        <div class="field" style="float: left;">
          <%= f.label :name %><br />
          <%= f.text_field :name, {:size => 20, :eradonly => true} %><br />
		  <%= f.label :resource_id %><br />
          <%= f.text_field :resource_id, :class => "phonebook" %><br />
		  <%= f.label :resource_type %><br />
          <%= f.text_field :resource_type, :class => "phonebook" %>
		  <div class="field">
          <%= f.label :user_tokens, "Users" %><br />
          <!-- %= f.collection_select :user_tokens, User.order(:username), :id, :username, {:selected => @role.user_tokens}, {:prompt => 'Select role users', :multiple => true, :size => 4} % --><br />
		  <%= f.collection_select :user_tokens, User.without_role, :id, :username, {:selected => @role.user_tokens}, {:prompt => 'Select role users', :multiple => true, :size => 4} %><br />
        </div>
        </div>
      </div>
    </fieldset>
  </div>

  <div style="clear: both;"></div>

  <div class="actions">
    <%= f.submit :class => 'button' %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<div id="mainbody">
<h2>Editing Role</h2>

<%= render 'form' %>

<div class="phonebook">
<%= link_to_modal 'Show', @role %> |
<%= link_to 'Back', roles_path %>
</div>
</div>

app/views/roles/index.html.erb
<div id="mainbody">
<h2>Listing roles</h2>
<p>
<div class="digg_pagination">
<%= will_paginate @roles %>&nbsp;<%= link_to 'New Role', new_role_path %>
</div>
</p>
<!-- %= "user logged in is #{current_user.username}.<br />\n" % -->
<p style="clear: both">
<br />
<strong>Warning:</strong> Be very, very careful when messing around with the roles.<br />
Role name changes have been disabled for because changing them will
prevent access to users belonging to that role.
<br />
If you really feel that a role name needs to be changed, contact the site administrator. 
<br />
<table class="phonebook" cellspacing="0">
  <thead>
    <tr>
      <th>Name</th>
	  <th></th>
	  <th>Resource id</th>
	  <th>Resource type</th>
	  <th></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr class="<%= cycle('ma_row_light', 'ma_row_dark') %>">
        <td><%= link_to_modal role.name, role %></td>
        <td>
        <% if can? :edit, Role %>
        <%= link_to image_tag("edit-icon.png", :size => "16x16", :title => "Edit details"), edit_role_path(role) %>
        <% end %>
        </td>
		<td>
			<% if role.resource_id %>
			<%= role.resource_id %>
			<% else %>
			All
			<% end %>
		</td>
		<td>
			<% if role.resource_type %>
			<%= role.resource_type %>
			<% else %>
			All
			<% end %>
		</td>
		 <% if can? :edit, Role %>
        <%= render :partial => "shared/delete_link", :object => role, :locals => {:display => "Delete #{role.id}" } %>
		<% else %>
		<td>&nbsp;</td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<p>
<div class="digg_pagination">
<%= will_paginate @roles %>&nbsp;<%= link_to 'New Role', new_role_path %>
</div>
</p>
<p style="clear: both">
</div>

app/views/roles/new.html.erb
<div id="mainbody">
<h2>New Role</h2>

<%= render 'form' %>

<div class="phonebook">
<%= link_to 'Back', roles_path %>
</div>
</div>

app/views/roles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>
<p>
  <strong>Resource id:</strong>
<% if @role.resource_id %>
<%= @role.resource_id %>
<% else %>
All
<% end %>
</p>
<p>
  <strong>Resource type:</strong>
<% if @role.resource_type %>
<%= @role.resource_type %>
<% else %>
All
<% end %>
</p>
<div class="phonebook">
<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>
</div>